# Generated by Django 4.2.7 on 2024-02-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_user_name_alter_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='username',
        ),
    ]
