# Generated by Django 4.2.7 on 2024-02-08 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='follows',
            new_name='following',
        ),
        migrations.AddField(
            model_name='follows',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
