# Generated by Django 4.2.7 on 2024-02-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_follows_follows_following_follows_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
