# Generated by Django 4.2.7 on 2024-02-23 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_follow_followers_alter_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='num_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
